name: Demo1
on:
  #push:
  #  branches:
  #    - main
  #    - jenk
  workflow_dispatch:
  
jobs:
  checking-pipeline:
    runs-on: ubuntu-latest

    steps:
    
    - name: Directory
      run: 'pwd'

    - name: List root files
      run: 'ls -al'

    - name: Node version
      run: "node --version"

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        #distribution: 'temurin'
        distribution: 'azul'

    - name: Java version
      run: "java -version"
      
    - name: Python version
      run: "python --version"
        
