name: Demo1
on:
  #push:
  #  branches:
  #    - main
  #    - jenk
  workflow_dispatch:
  
jobs:
  checking-pipeline:
    runs-on: ubuntu-latest

    steps:
    
    - name: Directory
      run: 'pwd'

    - name: List root files
      run: 'ls -al'

    - name: Previous Node version
      run: "node --version"

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: Updated Node version
      run: "node --version"

    - name: Previous version of Java
      run: "java -version"
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        #distribution: 'zulu'

    - name: Updated Java version
      run: "java -version"
      
    - name: Python version
      run: "python --version"
      
    - env:
        MESSAGE: "qwerty"
      run: "echo $MESSAGE"
